import Foundation

/// One entry of `preview-styles/styles.json` (generated by `make web` from `Web/src/preview/preview-styles/styles.json`,
/// the same file the preview page reads).
public struct PreviewStyle: Decodable, Identifiable, Equatable, Sendable {
    public let id: String
    public let name: String
    public let appearance: String  // "light" | "dark"
    public let hljs: String
    /// The style that stands in for this one on the other system appearance; nil = none.
    public let pair: String?
}

public enum PreviewStyles {
    private struct Registry: Decodable {
        let `default`: String
        let styles: [PreviewStyle]
    }

    private static let registry: Registry = {
        do {
            guard let url = WebAssets.url("preview-styles/styles.json") else { throw CocoaError(.fileNoSuchFile) }
            return try JSONDecoder().decode(Registry.self, from: Data(contentsOf: url))
        } catch {
            assertionFailure("preview-styles/styles.json unreadable: \(error)")  // shipped in the bundle; a build problem
            return Registry(default: "github", styles: [PreviewStyle(id: "github", name: "GitHub", appearance: "light", hljs: "github", pair: nil)])
        }
    }()

    /// UserDefaults keys of the choice (written by the app's settings, read by the app, export and Quick Look).
    public static let styleKey = "previewStyle"
    public static let followsSystemKey = "previewStyleFollowsSystem"

    public static var all: [PreviewStyle] { registry.styles }
    public static var defaultID: String { registry.default }

    /// The `(light, dark)` ids to hand to `MacDown2Preview.setStyle`. Fixed (`dark` nil) unless following the system and the
    /// chosen style has a partner; then both members of the pair, ordered by appearance, and the page switches by itself with
    /// `prefers-color-scheme`. An unknown id falls back to the default style.
    public static func resolve(id: String, followSystem: Bool) -> (light: String, dark: String?) {
        let chosen = all.first { $0.id == id } ?? all.first { $0.id == defaultID }!
        guard followSystem, let partner = all.first(where: { $0.id == chosen.pair }) else { return (chosen.id, nil) }
        return chosen.appearance == "dark" ? (partner.id, chosen.id) : (chosen.id, partner.id)
    }
}
