import Foundation
import WebAssets

/// `flavors.json`, generated by `Web/build.mjs` from `Web/src/<flavor>/manifest.json`.
/// Lets Quick Look and the CLI pick a flavor without linking any extension module.
public struct FlavorManifest: Sendable {
    public struct Entry: Sendable, Codable, Hashable {
        public var utTypes: [String]
        public var chunks: [String]
        public var stylesheets: [String]
        public var settingKey: String
    }

    public var entries: [FlavorID: Entry]

    public init(data: Data) throws {
        let decoded = try JSONDecoder().decode([String: Entry].self, from: data)
        entries = Dictionary(uniqueKeysWithValues: decoded.map { (FlavorID(rawValue: $0.key), $0.value) })
    }

    public static func bundled() throws -> FlavorManifest {
        guard let url = WebAssets.url("flavors.json") else { throw RenderError.missingAsset("flavors.json") }
        return try FlavorManifest(data: Data(contentsOf: url))
    }

    /// The flavor and chunks for a document type. Falls back to plain Markdown when no flavor
    /// claims the type or the owning extension's setting (`settingKey`) is off.
    public func resolve(utType: String, isEnabled: (String) -> Bool) -> (flavor: FlavorID, chunks: [String]) {
        for (id, entry) in entries where entry.utTypes.contains(utType) && isEnabled(entry.settingKey) {
            return (id, entry.chunks)
        }
        return (.markdown, [])
    }
}
